Repository deveelo/deveelo, pull requests merged in 2022-07, with the labels that each got.

#37 Bring Following System, Button Actions, Profile Social Lists to Prod
  README.md
  eros/accessToken.ts
  eros/components/Nav.tsx
  eros/components/Sidebar.tsx
  eros/components/micro/NameGroup.tsx
  eros/components/micro/ProfilePicture.tsx
  eros/components/micro/Result.tsx
  eros/components/micro/TextButton.tsx
  eros/components/micro/TitlebarButtons.tsx
  eros/components/micro/w40UserCard.tsx
  eros/components/minor/CardList.tsx
  eros/components/minor/Form.tsx
  eros/components/minor/SearchResults.tsx
  eros/components/minor/SocialList.tsx
  eros/hooks/backend/generated/graphql.tsx
  eros/hooks/backend/graphql/findCardUsersByIds.gql
  eros/hooks/backend/graphql/follow.gql
  eros/hooks/backend/graphql/randomMinProfile.gql
  eros/hooks/backend/graphql/unfollow.gql
  eros/hooks/bindTitlebar.ts
  eros/hooks/setSidebar.ts
  eros/hooks/socialhooks.ts
  eros/hooks/userChecks.ts
  eros/lib/userTypes.ts
  eros/package-lock.json
  eros/package.json
  eros/pages/[tag].tsx
  eros/pages/_app.tsx
  eros/public/fonts/DM/DMSans-Bold.ttf
  eros/public/fonts/DM/DMSans-BoldItalic.ttf
  eros/public/fonts/DM/DMSans-Italic.ttf
  eros/public/fonts/DM/DMSans-Medium.ttf
  eros/public/fonts/DM/DMSans-MediumItalic.ttf
  eros/public/fonts/DM/DMSans-Regular.ttf
  eros/public/resources/followbell.svg
  eros/styles/globals.css
  eros/styles/micro/w40.module.css
  eros/styles/minor/search.module.css
  eros/styles/minor/sociallist.module.css
  eros/styles/namegroup.module.css
  eros/styles/profilepicture.module.css
  eros/styles/sidebar.module.css
  eros/styles/status.module.css
  eros/styles/textbutton.module.css
  luna/src-tauri/tauri.conf.json
  vega/dist/graphql/middleware/isAuth.js
  vega/dist/graphql/middleware/isAuth.js.map
  vega/dist/graphql/resolvers/users.js
  vega/dist/graphql/resolvers/users.js.map
  vega/dist/graphql/typeDefs.js
  vega/dist/graphql/typeDefs.js.map
  vega/dist/util/validators.js
  vega/dist/util/validators.js.map
  vega/src/graphql/middleware/isAuth.ts
  vega/src/graphql/resolvers/users.ts
  vega/src/graphql/typeDefs.ts
  vega/src/util/auth.ts
  vega/src/util/validators.ts
Labels: 🍺 backend, 💪🥣 frontend, ✅ Fastrack, ⚡api, 🥇 priority: high

#39 Added Echo Build Script to Vega and Luna Package.json
  luna/package.json
  vega/package.json
Labels: ✅ Fastrack

#62 Unload Profile Edit form on User Display Switch
  eros/components/Sidebar.tsx
Labels: 💪🥣 frontend

#63 Migrate Middleware to Graphql-Tools Resolver Composition
  vega/dist/graphql/middleware/index.js
  vega/dist/graphql/middleware/index.js.map
  vega/dist/graphql/middleware/isAuth.js
  vega/dist/graphql/middleware/isAuth.js.map
  vega/dist/graphql/resolvers/posts.js
  vega/dist/graphql/resolvers/posts.js.map
  vega/dist/graphql/resolvers/uploads.js
  vega/dist/graphql/resolvers/uploads.js.map
  vega/dist/graphql/resolvers/users.js
  vega/dist/graphql/resolvers/users.js.map
  vega/dist/index.js
  vega/dist/index.js.map
  vega/package-lock.json
  vega/package.json
  vega/src/graphql/middleware/index.ts
  vega/src/graphql/middleware/isAuth.ts
  vega/src/graphql/resolvers/posts.ts
  vega/src/graphql/resolvers/uploads.ts
  vega/src/graphql/resolvers/users.ts
  vega/src/index.ts
  vega/src/util/middlewareType.ts
Labels: 🍺 backend, ⚡api, 🥇 priority: high
